service: apollo-federation-sample-app

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

functions:
  geocoder:
    handler: servers.geocoderServer
    events:
      - http:
          path: geocoder
          method: post
          cors: true
  weather:
    handler: servers.weatherServer
    events:
      - http:
          path: weather
          method: post
          cors: true
  gateway:
    handler: servers.gateway
    events:
      - http:
          path: /
          method: post
          cors: true

environment:
  BASE_URL:
    {
      "Fn::Join":
        [
          "",
          [
            " https://",
            { "Ref": "ApiGatewayRestApi" },
            ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}",
          ],
        ],
    }

plugins:
  - serverless-offline
