service: apollo-federation-sample-app

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    BASE_URL:
      {
        "Fn::Join":
          [
            "",
            [
              " https://",
              { "Ref": "ApiGatewayRestApi" },
              ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}",
            ],
          ],
      }

functions:
  geocoder:
    handler: servers.geocoderServer
    events:
      - http:
          path: /geocoder
          method: post
          cors: true
      - http:
          path: /geocoder
          method: get
          cors: true
  weather:
    handler: servers.weatherServer
    events:
      - http:
          path: /weather
          method: post
          cors: true
      - http:
          path: /weather
          method: get
          cors: true
  gateway:
    handler: servers.gatewayServer
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true

plugins:
  - serverless-offline
